### ISSUE TITLE
方便发一下数据么？

### ISSUE THREAD

**Issue by skyfully** [rottenivy/ST-matching#3]
最近在研究相关的论文，找不到合适的数据，请问能分享一下数据吗？十分感谢！

**Comment by rottenivy** [comment]
不好意思，数据是签过保密协议的，所以不能分享。

**Comment by rottenivy** [comment]
> 最近在研究相关的论文，找不到合适的数据，请问能分享一下数据吗？十分感谢！

不好意思，数据是签过保密协议的，所以不能分享。
